 name: Deploy to Cloud Run

  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

  env:
    PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    SERVICE_NAME: schedule-auto-feed
    REGION: asia-northeast1

  jobs:
    deploy:
      runs-on: ubuntu-latest

      permissions:
        contents: read
        id-token: write

      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY
   }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses:
  google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use gcloud as a
  credential helper
        run: gcloud auth configure-docker

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --source=. \
            --platform=managed \
            --region=$REGION \
            --allow-unauthenticated \
            --memory=1Gi \
            --cpu=1 \
            --timeout=3600 \
            --concurrency=10 \
            --min-instances=0 \
            --max-instances=10 \
            
  --set-env-vars="PROJECT_ID=$PROJECT_ID"

      - name: Show service URL
        run: |
          echo "Service URL: $(gcloud run services
   describe $SERVICE_NAME --platform=managed 
  --region=$REGION --format='value(status.url)')"
